CREATE TABLE Task
(
    id         BIGINT(20) NOT NULL AUTO_INCREMENT,
    course_id  BIGINT(20) NOT NULL,
    statement  VARCHAR(80) NOT NULL,
    task_order INT(11) NOT NULL,
    task_type  VARCHAR(30) NOT NULL,
    createdAt  DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT UNQ_STATEMENT UNIQUE (statement),
    CONSTRAINT FK_Course FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE
)